#!/bin/bash
#
RETVAL=0;
set -x
start() {
  echo “Starting Service”
  export SEED_NODE=akka.tcp://defend@127.0.0.1:3000
  export HOST=127.0.0.1
  export PORT=3004
  /usr/share/missiledefend-1.0.1/bin/missiledefend cc > /tmp/rmd.out 2>/tmp/rmd.err &
  echo "Started"
}

stop() {
  echo “Stopping Service”
  killall java
}

restart() {
  stop
  start
}

case "$1" in
start)
  start
;;
stop)
  stop
;;
restart)
  restart
;;
*)
echo "0=$0"
echo "1=$1"
echo ”Usage: $0 startstoprestart”
exit 1
esac

exit $RETVAL
